### ISSUE TITLE
Newer version of Docker

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/azure-sensible#1]
Hey @JimMadge 👋 We've started using this project on RangL to deploy a staging environment. We need to use Docker, specifically `docker-compose`, but the version installed by the below code block is too old. Can you show me what I'd need to tweak to get a newer/the latest version installed please?

https://github.com/alan-turing-institute/azure-sensible/blob/13a6cee9f7739a96345df6eb1d991e3e62d2b98c/ansible/ansible_vars.yaml#L41-L43

**Comment by JimMadge** [comment]
Hi Sarah, I'm excited (and a bit nervous) that you are using this.

I have built on these scripts to deploy a webapp using docker and docker-compose and I think there are a few tricks.

Could you say which docker/docker-compose versions you have after running ansible and which you need?

**Comment by sgibson91** [comment]
(My) Local versions:

```
$ docker --version 
Docker version 19.03.13, build 4484c46d9d

$ docker-compose --version
docker-compose version 1.27.4, build 40524192
```

Versions installed by Ansible:

```
$ docker --version
Docker version 19.03.13, build 4484c46d9d

$ docker-compose --version
docker-compose version 1.26.0, build d4451659
```

@DavidBeavan can you confirm this please? The versions aren't as different as I thought they would be?

**Comment by JimMadge** [comment]
The playbook uses [this role](https://github.com/geerlingguy/ansible-role-docker) to install docker and docker-compose.

The default compose version is 1.26.0, but you can use the `docker_compose_version:` variable to specify another version. You should be able put this in either the `ansible_vars.yaml` file or in the playbook itself in the `vars:` section.

```
docker_compose_version: "1.27.4"
```

I suspect quote marks will be necessary otherwise ansible will interpret the dots as a dictionary lookup.

**Comment by DavidBeavan** [comment]
The version RangL needs has a docker engine of 17.12.0 or higher: https://docs.docker.com/compose/compose-file/compose-versioning/#version-35

Do you know how that maps on to docker or docker-compose versions?

**Comment by sgibson91** [comment]
This page might be useful? https://docs.docker.com/engine/install/ubuntu/ I'm not sure if there's anything Ansible specific to support this though?

**Comment by JimMadge** [comment]
I _think_ the docker engine and docker versions are tied (although the cli program and the engine are separate packages on Ubuntu) so `docker --version` should give you the engine version.

You could double check with `apt show docker-ce | grep Version` and `apt show docker-ce-cli | grep Version`.

**Comment by sgibson91** [comment]
```
$ show docker-ce | grep Version

Command 'show' not found, but can be installed with:

sudo apt install mailutils-mh  # version 1:3.7-2.1, or
sudo apt install mmh           # version 0.4-2
sudo apt install nmh           # version 1.7.1-6
```

I tried all three installation methods and still can't get `show` to work? 🤦‍♀️

**Comment by sgibson91** [comment]
```
$ apt show docker-ce | grep Version
Version: 5:19.03.13~3-0~ubuntu-focal

$ apt show docker-ce-cli | grep Version
Version: 5:19.03.13~3-0~ubuntu-focal
```

Last night I did bump the Ubuntu image to 20.04 (we require another package that is not available on 18.04). Perhaps with this upgrade, `docker-compose` will now work? @DavidBeavan, do you have capacity to try?

**Comment by sgibson91** [comment]
I just ran `docker-compose up` for the platform repo with no issues so I think the Ubuntu image bump solved this. Thanks!

**Comment by JimMadge** [comment]
@sgibson91 I'm glad you found a solution. The Ubuntu version is a bit of a pain, 18.04 is showing its age but is still the default offering on Azure. The only 20.04 image I can find is a 'PRO' image with an associated cost.

I don't really want to make the default more expensive than it needs to be, but I can foresee a lot of potential problems due to the packages available on 18.04 being quite old.

**Comment by sgibson91** [comment]
I used this one? https://azuremarketplace.microsoft.com/en-us/marketplace/apps/canonical.0001-com-ubuntu-server-focal?tab=Overview

Terraform block is the following if you're interested

```
source_image_reference {
    publisher = "canonical"
    offer     = "0001-com-ubuntu-server-focal"
    sku       = "20_04-lts"
    version   = "latest"
}
```

**Comment by JimMadge** [comment]
Well that's embarrassing, I was certain there was only the PRO offering for 20.04 when I last looked. I'll add this to the main branch. Thanks @sgibson91!
